export enum MetricEnum {
  followers = 'followers',
  reach = 'reach',
  impressions = 'impressions',
  engagement = 'engagement',
  engagement_rate = 'engagement_rate',
  sessions = 'sessions',
  conversions = 'conversions',
  spend = 'spend',
  clicks = 'clicks',
  likes = 'likes',
  comments = 'comments',
  shares = 'shares',
  saves = 'saves',
  video_views = 'video_views',
  profile_views = 'profile_views',
  website_clicks = 'website_clicks',
  total_interactions = 'total_interactions',
  new_follows = 'new_follows',
  following = 'following',
  total_likes = 'total_likes',
  video_count = 'video_count',
  // Web (GA4) metrics
  users = 'users',
  page_views = 'page_views',
  bounce_rate = 'bounce_rate',
  engagement_rate_pct = 'engagement_rate_pct',
  avg_session_duration = 'avg_session_duration',
}
